[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "4ebe610b1b1a2b18fd4caae61e6b6db470a8f828"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "a75b6697676d622f5f4441079a51b36fe7cdcb2cf1ea38feeda87ade5ec9309d"
    url = "https://github.com/olynch/Raylib_jll.jl/releases/download/Raylib-v3.7.0+0/Raylib.v3.7.0.x86_64-linux-gnu.tar.gz"
